### ISSUE TITLE
Extend JS JWT hardcoded secret rule

### ISSUE THREAD

**Issue by elsapet** [Bearer/bearer-rules#20]
Extend `javascript_lang_jwt_hardcoded_secret` rule to include pattern from Jose library, [for example](https://github.com/panva/jose/blob/main/docs/classes/jwt_sign.SignJWT.md)

```
jose.SignJWT().....sign(<some hardcoded secret>)
```

Prior to the rules migration, we were allegedly "supporting" this but with outdated rule syntax 

```
  - pattern: |
      $<JOSE_SIGN_JWT>.sign($<STRING_LITERAL>)
    filters:
      - variable: JOSE_SIGN_JWT
        pattern:
          - |
            jose.SignJWT().$<...>
      - variable: STRING_LITERAL
        detection: string_literal
        contains: false
```

It may be difficult to support the multiple method calls with current updates to the variable name joining, but we could support one non-"sign" method call for the meanwhile.
