### ISSUE TITLE
Rules for JQuery code

### ISSUE THREAD

**Issue by drupal-spider** [Bearer/bearer-rules#277]
Thanks for the great tool.

I wonder if there is a rule for scanning Jquery codes?

For example, the following Jquery code is concerned. 

```javascript
const inputString = $("#userInputID").val(); 
$( "div.demo-container" ).html(inputString);
```

**Comment by cfabianski** [comment]
Hey @drupal-spider 

The tool can be used for any JS code.

To catch this, you can write a custom rule 

```yaml
patterns:
  - pattern: $<_>.html($<USER_INPUT>)
    filters:
      - variable: USER_INPUT
        detection: test_user_input
auxiliary:
  - id: test_user_input
    patterns:
      - pattern: $($<_>).val()
```

Best
